name: Bug Report
description: Please find this form to report an unexpected behavior or suspected bug. 
labels: [bug, need triage]
title: 'Bug report-'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using the CAF Terraform module! 

        Please note the following repo might need to updated also:

        * [Missing naming convention provider](https://github.com/aztfmod/terraform-provider-azurecaf)
        * [Rover and state management](https://github.com/aztfmod/rover)
        * [Landing zones logic](https://github.com/Azure/caf-terraform-landingzones)

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: community
    attributes:
      label: Community Note
      description: This note is for the community, please leave and skip this.
      value: |
        <!--- Please keep this note for the community --->

        * Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment

        <!--- Thank you for keeping this note for the community --->
    validations:
      required: true
  - type: input
    id: moduleversion
    attributes:
      label: Version of the module you are using
      description: Which module version are you using?
      placeholder: 5.5.0
    validations:
      required: true
  - type: input
    id: rover
    attributes:
      label: Rover Version
      description: Which rover version are you using?
      placeholder: 'aztfmod/rover:1.1.7-2203.2311'
    validations:
      required: false
  - type: input
    id: terraform
    attributes:
      label: Terraform Version
      description: Which Terraform version are you using? (leave blank if you provided rover version)
      placeholder: 1.0.0
    validations:
      required: false
  - type: input
    id: azurerm
    attributes:
      label: AzureRM Provider Version
      description: Which AzureRM Provider version are you using? (leave blank if you provided module version)
      placeholder: 3.0.0
    validations:
      required: false
  - type: input
    id: resource
    attributes:
      label: Affected Resource(s)/Data Source(s)
      description: Please list the affected resources and/or data sources.
      placeholder: azurerm_XXXXX
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Terraform Configuration Files
      description: |
        Please provide a minimal Terraform configuration that can reproduce the issue.

        For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
      render: hcl
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should have happened?
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the steps required to reproduce the issue, e.g.

        1. `terraform apply`
  - type: input
    id: facts
    attributes:
      label: Important Factoids
      description: |
        Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government?
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?